export default {
  amanda: [
    { id: '01', board: 'Deploy', date: 'March 7, 2017', text: 'And yay! That giphy is now off of my screen...Gary, No!' },
    { id: '02', board: 'Deploy', date: 'September 25, 2017', text: 'You could probably get arrested for doing that…But I guess they’d probably stop.' },
    { id: '03', board: 'Deploy', date: 'October 3, 2017', text: 'I always thought that Duplo was a knock off lego' },
    { id: '04', board: 'Deploy', date: 'February 3, 2018', text: 'banana phone. I couldn\'t resist' },
    { id: '05', board: 'Quote Board', date: 'March 21, 2017', text: 'I’ve got to hear this story.  Well, maybe.' },
    { id: '06', board: 'Quote Board', date: 'June 14, 2017', text: '“In general, I’d like to avoid using ‘pimp’ as a term of endearment.” -Robb' },
    { id: '07', board: 'Quote Board', date: 'July 11, 2017', text: '“I’m a swirl guy.” -Robb' },
    { id: '08', board: 'Quote Board', date: 'August 29, 2017 ', text: '“I got so many liquids going on over here.” -Robb' },
    { id: '09', board: 'Quote Board', date: 'Aug 10, 2018', text: 'I like what you did there with "laser" hahahaha' },
    { id: '011', board: 'Passenger Restarted', date: 'June 30, 2017', text: '“grizzly bears with dementia on drugs”' },
  ],
  gary: [
    { id: '11', board: 'ADS', date: 'February 19, 2019', text: 'I like acid rain. :)' },
    { id: '12', board: 'Deploy', date: 'January 20, 2017', text: 'Climb onto my space rocket...You need no put money in my pocket. The door is closed, I just lock it.' },
    { id: '13', board: 'Deploy', date: 'March 1, 2017', text: 'fuckin kangaroos…' },
    { id: '14', board: 'Deploy', date: 'March 24 2017', text: 'FUCK PRAWN!' },
    { id: '15', board: 'Deploy', date: 'July 31, 2017', text: 'Alcohol poisoning will do that.' },
    { id: '16', board: 'Deploy', date: 'August 14, 2017', text: 'Well, fuck fuckity fuck fuck.' },
    { id: '17', board: 'Deploy', date: 'September 14, 2017', text: 'Why is Robb cryin? Cause he just got dunked on!' },
    { id: '18', board: 'Deploy', date: ' October 18, 2017', text: 'YOU SUNK MY BATTLESHIT!' },
    { id: '19', board: 'Deploy', date: ' November 14, 2017', text: 'Yeah, "I slipped and fell into the skirmishfucking" does not sound very plausible.' },
    { id: '111', board: 'Deploy', date: 'January 31, 2019', text: 'Just make sure she is using those kindergarten scissors.' },
    { id: '112', board: 'Football', date: ' October 6, 2018', text: 'It doesn’t count to call yourself hard due to the amount of heavy metals you ingest.' },
    { id: '113', board: 'Football', date: 'January 15, 2019', text: 'Is Michigan just having a fire sale on their coaches?' },
    { id: '114', board: 'Quote Board', date: 'June 21, 2017', text: '"Pecker Off, Boy!" -Mike (In his best Queeny voice) ' },
    { id: '115', board: 'Quote Board', date: 'June 21, 2017', text: '"Since it\'s so small, I think it\'s Evan\'s." -Robb' },
    { id: '116', board: 'Quote Board', date: 'July 11, 2017', text: '"I just blue myself!" -Robb -Quoting Tobias Funke, but with blue teeth and mouth from eating a sucker, and right after saying "I\'m a swirl guy." ' },
    { id: '117', board: 'Quote Board', date: 'July 12, 2017', text: '"We need more twat." -Robb' },
    { id: '118', board: 'Quote Board', date: 'August 7, 2017', text: '"I guess there really is not much you can do with floppy dick." -Robb' },
    { id: '119', board: 'Quote Board', date: 'August 25, 2017', text: '"You\'ve played with wooly willy in your lifetime." -Robb' }
  ],
  robb: [
    { id: '21', board: 'Deploy', date: 'October 11, 2016', text: 'I think Jared has been Flandered' },
    { id: '22', board: 'Deploy', date: 'October 26, 2016', text: 'I’m alright - Gary is in the restroom' },
    { id: '23', board: 'Deploy', date: 'May 5, 2017', text: 'Haha we were hearing Henry\'s possum impression.  It was pretty incredible' },
    { id: '24', board: 'Deploy', date: 'October 2, 2017', text: 'I\'m down.  I just figured I was the automated snowflake friend' },
    { id: '25', board: 'Deploy', date: 'October 24, 2017', text: 'YOLO' },
    { id: '26', board: 'Deploy', date: 'October 17, 2018', text: 'That\'s Meredith. I don\'t think you want to be Meredith.' },
    { id: '27', board: 'Football', date: 'December 27, 2017', text: 'The state of Florida needs to learn how to count' },
    { id: '28', board: 'Football', date: ' September 24, 2018', text: 'Well, Colorado left you and took all their scandals with them, so that\'s not fair' },
    { id: '29', board: 'Football', date: 'October 1, 2019', text: 'Gary. You did a bad to Jared!' },
    { id: '211', board: 'Football', date: 'January 19, 2019', text: 'haha, you guys are assholes but I love you' },
    { id: '212', board: 'Quote Board', date: 'October 23, 2017', text: '"Didn\'t your mother give us a dutch oven once?" - Robb, to his wife this weekend.' },
    { id: '213', board: 'Quote Board', date: 'March 14, 2017', text: 'For context, this was said in reference to balls.  and Mantis Shrimp' },
    { id: '214', board: 'Quote Board', date: 'June 15, 2017', text: '"It\'s a ho wide world that we livin\' in"' },
    { id: '215', board: 'Quote Board', date: 'August 30, 2017', text: 'I said neither of these things, haha' },
    { id: '216', board: 'Passenger Restarted', date: 'June 30, 2017', text: '(but not the good kind of dementia-lessening drugs)' }
  ],
  jared: [
    { id: '31', board: 'Daily Update', date: 'December 22, 2016', text: 'I wanted "Funky Cold Medina"!' },
    { id: '32', board: 'Daily Update', date: 'August 24, 2017', text: 'I sometimes feel like Shakespeare plays were the precursor to the Darwin Awards' },
    { id: '33', board: 'Deploy', date: 'December 6, 2016', text: 'Robb\'s consent is everyone\'s consent' },
    { id: '34', board: 'Deploy', date: 'December 27, 2016', text: 'It\'s okay to not confuse me with your linguistic alchemy' },
    { id: '35', board: 'Deploy', date: 'March 7, 2017', text: 'So far, I have successfully refrained from changing the "deploy" channel\'s name to "shit_the_flowers". I get points for that, right?' },
    { id: '36', board: 'Deploy', date: 'May 1, 2017', text: 'Amanda\'s a dolphin-sympathizer.' },
    { id: '37', board: 'Deploy', date: 'June 23, 2017', text: 'Alright, that\'s a pretty convincing argument, so everyone\'s rehired, and we still all get raises, right, Mike?' },
    { id: '38', board: 'Deploy', date: 'October 17, 2017', text: '(not sure if the anger is at Mike for deleting my code or myself for taking 3 years to notice)' },
    { id: '39', board: 'Deploy', date: 'November 17, 2017', text: 'Sorry, distracted by Star Trek. Yeah, that looks good' },
    { id: '311', board: 'Deploy', date: 'January 10, 2018', text: 'My goodness man. I know things are bad in the world, but are we really ready to take such drastic action as deploying Gary?!' },
    { id: '312', board: 'Deploy', date: 'February 22, 2019', text: '"Information Whiskey" is the name of my forthcoming poetry collection' },
    { id: '313', board: 'Football', date: 'September 22, 2018', text: 'I think I\'ve successfully trolled myself, as I now have a window with the score opened.' },
    { id: '314', board: 'Football', date: 'October 1, 2018', text: 'I never understand what\'s happening in the channel' },
    { id: '315', board: 'Football', date: 'Oct 22, 2018', text: 'Well, in a fight between Ahmadinejad and Toby Keith, I think who wins is everybody else' },
    { id: '316', board: 'Football', date: 'December 7, 2018', text: 'Big 10: Creepy or just bad at math? We report. You decide' },
    { id: '317', board: 'Football', date: 'February 24, 2019', text: '"Explaining Human Men", by Robb. Entire contents: "His dick is the I."' },
    { id: '318', board: 'Quote Board', date: 'April 12, 2017', text: '"It wasn\'t a teachable moment, so I just lied" - robb' },
    { id: '319', board: 'Quote Board', date: 'April 24, 2017', text: '"We\'re probably better off with a drugged up Robb" - Amanda' },
    { id: '3111', board: 'Quote Board', date: 'May 11, 2017', text: '"I always wake up and I\'m like where am I, what bed am I in?... why is there underwear in my face?" - Robb' },
    { id: '3112', board: 'Societal Issues', date: 'January 4, 2017', text: 'Robb twerked Gary at Evan???' },
    { id: '3113', board: 'Societal issues', date: 'June 5, 2017', text: 'How to know the write for Reuters is old and bitter: "Snapchat is popular among people under 30 who enjoy applying bunny faces and vomiting rainbows onto their pictures."' }
  ],
  mike: [
    { id: '41', board: 'Daily Update', date: 'December 22, 2016', text: 'I\'m not really sure what\'s going on here.  But if we\'re guessing songs.. what am I?' },
    { id: '42', board: 'ADS', date: 'February 19, 2019', text: 'Yay for kidney stones' },
    { id: '43', board: 'Quote Board', date: 'June 15, 2017', text: '“Fancy cars, women, and the caviar.  They who we are, ‘cause we’re pimpin’ all over the world.”' },
    { id: '44', board: 'Deploy', date: 'November 22, 2016', text: 'It\’s 5:57am CST, I’m deploying and none of you can stop me.  Well, I guess Jared could block my IP.' },
    { id: '45', board: 'Deploy', date: 'February 16, 2017', text: 'I approve of this message.' },
    { id: '46', board: 'Deploy', date: 'March 27, 2017', text: 'I just realized I missed a beautiful opportunity last night to say, "Thanks, Other Mike."' },
    { id: '47', board: 'Deploy', date: 'September 25, 2017', text: 'Avoiding using the “D” word, Jared?' },
    { id: '48', board: 'Deploy', date: 'October 24, 2017', text: 'I’m glad we don’t have an HR department.' },
    { id: '49', board: 'Deploy', date: 'December 13, 2017', text: 'May I rephrase this morning’s email?  “Mike, Given the changes yesterday to growing Orange trees, I am still unclear of how to fly to the moon.”' },
    { id: '411', board: 'Deploy', date: 'July 19, 2019', text: 'I have questions' },
    { id: '412', board: 'Football', date: 'March 18, 2018', text: 'Who are those people?  Did Michigan win or something?' },
    { id: '413', board: 'Football', date: 'August 25, 2018', text: 'There is entirely too much talk about Michigan making it to the playoff.' },
    { id: '414', board: 'Football', date: 'October 3, 2018', text: 'Robb went mean. It’s okay, Amanda, just respond with something like “the odds of Jim Harbaugh beating OSU are one in a never ever gunna happen”' },
    { id: '415', board: 'Football', date: 'January 10, 2019', text: 'So dramatic.  Michigan fans: worse than middle school girls who are just learning about boys' }
  ]
};